name: jacoco test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:11.0.11
      env:
        # コンテナ内では`~`が`/github/home`となるため、キャッシュディレクトリの辻褄をここで合わせる
        GRADLE_USER_HOME: /github/home/.gradle


    steps:
    # actions/checkout@v2の実行のため、コンテナ内に少なくともtarコマンドが必要
    # actions/cache@v1の実行のため、コンテナ内にtar, gzipコマンドが必要
    - name: Install tar, gzip for actions/checkout and actions/cache
      run: yum install -y tar gzip

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: pwd
      run: pwd

    - name: list
      run: ls -la

    - name: test code
      run: ./gradlew clean test jacocoTestReport jacocoTestCoverage

    - name: check
      run: ls -la ./build/


    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: 28a57836-ef70-461c-8a4e-cb91b9a8de70
        files: ./build/jacoco.xml
        flags: unittests
        version: "v0.1.15"
        fail_ci_if_error: true
        name: codecov-umbrella
